site_name: ticket-reservation-app
site_description: ticket reservation app using celery and django
repo_url: https://github.com/hyoinandout/django-rest
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/hyoinandout">hyoinandout</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
